name: Build README

on:
  schedule:
    - cron: '0 0 */1 * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual trigger
  push:
    branches: [ master ]
    paths:
      - 'build_readme.py'
      - 'requirements.txt'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install PDM
      run: curl -sSL https://pdm-project.org/install-pdm.py | python3 -

    - name: Install dependencies
      run: pdm install

    - name: Update README
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: pdm run python build_readme.py

    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "ci: update profile (automatically)"
          git push
        fi
