on:
  schedule:
    - cron:  '0 16 * * *'
  push:
    branches:    
      - master
  workflow_dispatch:

jobs:
  fetch-upstream:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Fetch Upstream
      uses: bdougie/fetch-upstream@master
      with:
        upstream: babel/babel
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
